apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-mtls
  namespace: nginx-mtls
spec:
  host: nginx.${OCP_APPS_DOMAIN}
  port:
    targetPort: 443
  to:
    kind: Service
    name: nginx-mtls
    weight: 100
  wildcardPolicy: None
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None