apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-http
  namespace: nginx
spec:
  host: nginx.${OCP_APPS_DOMAIN}
  to:
    kind: Service
    name: nginx
    weight: 100
  port:
    targetPort: 80
  wildcardPolicy: None