##################################################################################################
# details-custom service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: details-custom
  labels:
    app: details-custom
    service: details-custom
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details-custom
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details-custom
  labels:
    account: details-custom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-custom-v1
  labels:
    app: details-custom
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details-custom
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: details-custom
        version: v1
    spec:
      serviceAccountName: bookinfo-details-custom
      containers:
      - name: details-custom
        image: maistra/examples-bookinfo-details-v1:2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
##################################################################################################
# Reviews-custom service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reviews-custom
  labels:
    app: reviews-custom
    service: reviews-custom
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews-custom
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews-custom
  labels:
    account: reviews-custom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-custom-v1
  labels:
    app: reviews-custom
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-custom
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: reviews-custom
        version: v1
    spec:
      serviceAccountName: bookinfo-reviews-custom
      containers:
      - name: reviews-custom
        image: maistra/examples-bookinfo-reviews-v1:2.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-custom-v2
  labels:
    app: reviews-custom
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-custom
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: reviews-custom
        version: v2
    spec:
      serviceAccountName: bookinfo-reviews-custom
      containers:
      - name: reviews-custom
        image: maistra/examples-bookinfo-reviews-v2:2.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-custom-v3
  labels:
    app: reviews-custom
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-custom
      version: v3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: reviews-custom
        version: v3
    spec:
      serviceAccountName: bookinfo-reviews-custom
      containers:
      - name: reviews-custom
        image: maistra/examples-bookinfo-reviews-v3:2.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---